version: '3.8'

services:
  # Service untuk aplikasi Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filament-plugin-test
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    command: "php artisan serve --host=0.0.0.0 --port=8000"

  # Service untuk database MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db-filament
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_ROOT_PASSWORD: 'your_strong_password'
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data: